module.exports = {
	setupFilesAfterEnv: ["@testing-library/react/cleanup-after-each"],
	roots: ["<rootDir>/src"],
	verbose: false,
	coverageDirectory: "./coverage/",
	collectCoverageFrom: ["src/**/*.{ts,tsx}"],
	collectCoverage: true,
	modulePathIgnorePatterns: ["_testHelpers"],
	transform: {
		"^.+\\.tsx?$": "ts-jest",
	},
	moduleNameMapper: {
		"^.+\\.(css|less|scss)$": "identity-obj-proxy",
		"^assets(.*)$": "<rootDir>/src/assets$1",
		"^components(.*)$": "<rootDir>/src/components$1",
		"^configuration(.*)$": "<rootDir>/src/configuration$1",
		"^containers(.*)$": "<rootDir>/src/containers$1",
		"^helpers(.*)$": "<rootDir>/src/helpers$1",
		"^pages(.*)$": "<rootDir>/src/pages$1",
		"^public(.*)$": "<rootDir>/src/public$1",
		"^stores(.*)$": "<rootDir>/src/stores$1",
		"^styles(.*)$": "<rootDir>/src/styles$1",
		"^types(.*)$": "<rootDir>/src/types$1",
	},
};
