# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'ios-runtime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-runtime
  pod 'Alamofire', '~> 5.4'
  pod 'KeychainSwift'

  target 'ios-runtimeTests' do
    # Pods for testing
  end

end
