name: docs_dev
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js 📦
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies 🔧
        run: |
          npm ci --include=dev

      - name: Build docs 🚚
        run: |
          pip install mkdocs-material
          sed -i -e "s/sdkgen.github.io/sdkgen.github.io\/dev/g" mkdocs.yml
          mkdocs build

      - name: Build playground 🌎
        run: |
          npm run build
          sed -i -E 's_(<base href=")/(">)_\1/dev/playground/\2_' packages/playground/dist/index.html

      - name: Setup SSH deploy key 🔑
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SDKGEN_DOCS_DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "GIT_SSH_COMMAND=ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=accept-new" >> "$GITHUB_ENV"

      - name: Prepare deploy 📦
        run: |
          git clone --depth 1 -b main git@github.com:sdkgen/sdkgen.github.io.git
          rm -rf sdkgen.github.io/dev
          mv site sdkgen.github.io/dev
          mv packages/playground/dist/ sdkgen.github.io/dev/playground/

      - name: Deploy 🚀
        run: |
          cd sdkgen.github.io
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "deploy dev"
            git push;
          fi
