export const animals = [
  "Aardvark",
  "African Elephant",
  "African Grey Parrot",
  "African Lion",
  "African Wild Dog",
  "Agouti",
  "Albatross",
  "Alligator",
  "Allosaurus",
  "Alpaca",
  "Amazon Dolphin",
  "Amazon Parrot",
  "American Alligator",
  "American Bison",
  "American Crow",
  "American Kestrel",
  "American Robin",
  "Anaconda",
  "Andean Condor",
  "Anglerfish",
  "Anhinga",
  "Anole",
  "Ant",
  "Anteater",
  "Antelope",
  "Arapaima",
  "Arctic Fox",
  "Arctic Wolf",
  "Argus",
  "Armadillo",
  "Arowana",
  "Asian Elephant",
  "Assassin Bug",
  "Auk",
  "Axis Deer",
  "Axolotl",
  "Aye Aye",
  "Badger",
  "Bald Eagle",
  "Baldpate",
  "Ball Python",
  "Bandicoot",
  "Barn Owl",
  "Barn Swallow",
  "Barnacle",
  "Barred Owl",
  "Basking Shark",
  "Bat",
  "Beaver",
  "Beluga Whale",
  "Bengal Tiger",
  "Bichir",
  "Bighorn Sheep",
  "Binturong",
  "Bird of Paradise",
  "Black Bear",
  "Black Buck",
  "Black Dolphin",
  "Black Footed Ferret",
  "Black Mamba",
  "Black Racer",
  "Black Rail",
  "Black Rhino",
  "Black Swan",
  "Black Swift",
  "Black Widow Spider",
  "Blackbird",
  "Blacktip Shark",
  "Blobfish",
  "Blue Bull (Nilgai)",
  "Blue Duck",
  "Blue Footed Booby",
  "Blue Jay",
  "Blue Shark",
  "Blue Tongue Skink",
  "Blue Whale",
  "Bluebird",
  "Boa Constrictor",
  "Bobcat",
  "Bobwhite Quail",
  "Bongo",
  "Bonobo",
  "Booby Bird",
  "Bottlenose Dolphin",
  "Bowfin",
  "Box Turtle",
  "Brant",
  "Brown Bear",
  "Brown Jay",
  "Brown Pelican",
  "Brown Snake",
  "Budgie",
  "Buffalo",
  "Bufflehead",
  "Bull Shark",
  "Bullfrog",
  "Bullsnake",
  "Bunting",
  "Burmese Python",
  "Burrowing Owl",
  "Bush Dog",
  "Bushmaster",
  "Cacique",
  "Caiman",
  "California Condor",
  "California Quail",
  "Camel Spider",
  "Canada Goose",
  "Canary",
  "Cane Toad",
  "Canvasback",
  "Capuchin",
  "Capybara",
  "Caracal",
  "Cassowary",
  "Cat Shark",
  "Cat Snake",
  "Catbird",
  "Cave Bear",
  "Chachalaca",
  "Chameleon",
  "Chamois",
  "Cheetah",
  "Chickadee",
  "Chimpanzee",
  "Chinchilla",
  "Chukar",
  "Cinnamon Teal",
  "Clouded Leopard",
  "Coati",
  "Cobra",
  "Cockatiel",
  "Cockatoo",
  "Coelacanth",
  "Cooper's Hawk",
  "Coot",
  "Coral Snake",
  "Cormorant",
  "Corn Snake",
  "Cottonmouth",
  "Cottontail",
  "Cow",
  "Coyote",
  "Crake",
  "Crane",
  "Crested Gecko",
  "Crocodile",
  "Crocodile Skink",
  "Crow",
  "Cuckoo Bird",
  "Curlew",
  "Cuscus",
  "Deer Mouse",
  "Desert Tortoise",
  "Diamondback Rattlesnake",
  "Dik Dik",
  "Dilophosaurus",
  "Dimetrodon",
  "Dingo",
  "Dipper",
  "Dodo",
  "Dogfish",
  "Donkey",
  "Dove",
  "Drill",
  "Duck",
  "Dugong",
  "Dwarf Hamster",
  "Eagle",
  "Eagle Owl",
  "Echidna",
  "Eider",
  "Eland",
  "Elephant Seal",
  "Elephant Shrew",
  "Elk",
  "Emperor Penguin",
  "Emu",
  "Ermine",
  "Falcon",
  "Fallow Deer",
  "Fennec Fox",
  "Ferret",
  "Finch",
  "Fisher",
  "Fishing Cat",
  "Flamingo",
  "Flycatcher",
  "Flying Dragon",
  "Flying Fox",
  "Flying Squirrel",
  "Fossa",
  "Frigate Bird",
  "Frilled Lizard",
  "Frilled Shark",
  "Frog",
  "Gaboon Viper",
  "Gadwall",
  "Gannet",
  "Garter Snake",
  "Gaur",
  "Gazelle",
  "Gecko",
  "Genet",
  "Gharial",
  "Ghost Bat",
  "Giant Ground Sloth",
  "Giant Salamander",
  "Gibbon",
  "Gila Monster",
  "Giraffe",
  "Glow Worm",
  "Gnu",
  "Goblin Shark",
  "Golden Cat",
  "Golden Eagle",
  "Golden Pheasant",
  "Goldeneye",
  "Goldfinch",
  "Goliath Birdeater",
  "Goose",
  "Gopher",
  "Gopher Snake",
  "Gorilla",
  "Goshawk",
  "Grackle",
  "Grass Snake",
  "Gray Fox",
  "Gray Owl",
  "Great Blue Heron",
  "Great White Shark",
  "Green Anaconda",
  "Green Frog",
  "Green Jay",
  "Green Turtle",
  "Greenland Shark",
  "Grouse",
  "Guan",
  "Guanaco",
  "Guinea Pig",
  "Hagfish",
  "Hammerhead Shark",
  "Hamster",
  "Harlequin Duck",
  "Harpy Eagle",
  "Harrier Hawk",
  "Hawk",
  "Hedgehog",
  "Hellbender",
  "Hercules Beetle",
  "Hermit Crab",
  "Heron",
  "Hippopotamus",
  "Honey Badger",
  "Horny Toad",
  "Horse",
  "House Finch",
  "House Martin",
  "House Sparrow",
  "House Wren",
  "Howler Monkey",
  "Hummingbird",
  "Humpback Whale",
  "Huntsman Spider",
  "Hyena",
  "Ibis",
  "Iguana",
  "Impala",
  "Indian Elephant",
  "Irish Elk",
  "Island Fox",
  "Jackal",
  "Jackrabbit",
  "Jaeger",
  "Jaguar",
  "Kaka",
  "Kakapo",
  "Kangaroo",
  "Kangaroo Rat",
  "Kea",
  "Key Deer",
  "Killdeer",
  "Killer Bee",
  "Killer Whale (Orca)",
  "King Cobra",
  "King Eider",
  "Kingfisher",
  "Kinkajou",
  "Kit Fox",
  "Kite",
  "Kiwi",
  "Koala",
  "Kob",
  "Kodiak Bear",
  "Komodo Dragon",
  "Kookaburra",
  "Kudu",
  "Ladybug",
  "Lake Sturgeon",
  "Lamprey",
  "Leatherback Sea Turtle",
  "Lemming",
  "Lemon Shark",
  "Lemur",
  "Leopard",
  "Leopard Cat",
  "Leopard Gecko",
  "Leopard Seal",
  "Leopard Shark",
  "Lionfish",
  "Lizard",
  "Llama",
  "Loggerhead Turtle",
  "Loon",
  "Loris",
  "Lovebird",
  "Lynx",
  "Lyrebird",
  "Macaque",
  "Macaw",
  "Magpie",
  "Mako Shark",
  "Mallard Duck",
  "Mamba",
  "Manatee",
  "Mandarin Duck",
  "Mandrill",
  "Maned Wolf",
  "Manta Ray",
  "Map Turtle",
  "Mara",
  "Marmoset",
  "Marmot",
  "Marten",
  "Mastadon",
  "Meadowlark",
  "Megalodon",
  "Merganser",
  "Merlin",
  "Milk Snake",
  "Mink",
  "Moa",
  "Moccasin",
  "Mockingbird",
  "Mole",
  "Mole Rat",
  "Moloch",
  "Mongoose",
  "Monitor Lizard",
  "Monkfish",
  "Moon Bear",
  "Moose",
  "Moray Eel",
  "Mountain Goat",
  "Mountain Lion",
  "Mountain Sheep",
  "Mourning Dove",
  "Mule",
  "Mule Deer",
  "Muscovy Duck",
  "Musk Ox",
  "Muskrat",
  "Naked Mole Rat",
  "Narwhal",
  "Nene",
  "Newt",
  "Night Heron",
  "Nighthawk",
  "Northern Cardinal",
  "Nuthatch",
  "Nutria Rat",
  "Ocelot",
  "Okapi",
  "Opossum",
  "Orangutan",
  "Oriole",
  "Osprey",
  "Ostrich",
  "Paca",
  "Pack Rat",
  "Pacman Frog",
  "Painted Turtle",
  "Panda Bear",
  "Pangolin",
  "Panther Chameleon",
  "Parrot",
  "Parrotfish",
  "Partridge",
  "Peacock",
  "Pelican",
  "Peregrine Falcon",
  "Petrel",
  "Pheasant",
  "Pigeon",
  "Pika",
  "Pileated Woodpecker",
  "Pintail",
  "Piranha",
  "Pit Viper",
  "Pitta",
  "Platypus",
  "Plover",
  "Poison Dart Frog",
  "Polar Bear",
  "Porcupine",
  "Porpoise",
  "Possum",
  "Prairie Chicken",
  "Proboscis Monkey",
  "Ptarmigan",
  "Puffin",
  "Purple Martin",
  "Python",
  "Quagga",
  "Quetzal",
  "Quokka",
  "Rabbit",
  "Raccoon",
  "Rail",
  "Rainbow Snake",
  "Rat Snake",
  "Rat Squirrel",
  "Raven",
  "Red Deer",
  "Red Fox",
  "Red Panda",
  "Red Squirrel",
  "Red Tailed Hawk",
  "Red Wolf",
  "Redwing",
  "Reef Shark",
  "Reindeer",
  "Reticulated Python",
  "Rhea",
  "Rhinoceros",
  "Ringtail",
  "River Otter",
  "Roadrunner",
  "Ruddy Duck",
  "Ruff",
  "Russian Tortoise",
  "Saber Tooth Tiger",
  "Sable",
  "Sage Grouse",
  "Saiga Antelope",
  "Salamander",
  "Saltwater Crocodile",
  "Sambar",
  "Sand Boa",
  "Sand Cat",
  "Sanderling",
  "Sandhill Crane",
  "Sandpiper",
  "Savannah Monitor",
  "Sawfish",
  "Scarlet Ibis",
  "Scorpion",
  "Screamer",
  "Screech Owl",
  "Sea Dragon",
  "Sea Eagle",
  "Sea Horse",
  "Sea Lion",
  "Sea Otter",
  "Sea Snake",
  "Sea Turtle",
  "Serval",
  "Shearwater",
  "Shoebill Stork",
  "Shrew",
  "Shrike",
  "Siberian Tiger",
  "Siren",
  "Skate",
  "Skimmer",
  "Skink",
  "Skunk",
  "Sloth",
  "Sloth Bear",
  "Slow Loris",
  "Snake",
  "Snapping Turtle",
  "Snipe",
  "Snow Goose",
  "Snow Leopard",
  "Snowy Owl",
  "Softshell Turtle",
  "Sora",
  "Sperm Whale",
  "Spider Monkey",
  "Spinosaurus",
  "Spoonbill",
  "Springbok",
  "Squirrel",
  "Squirrel Monkey",
  "Starling",
  "Stegosaurus",
  "Stingray",
  "Stork",
  "Sturgeon",
  "Sugar Glider",
  "Sulcata Tortoise",
  "Sun Bear",
  "Sunbird",
  "Sunfish",
  "Swallow",
  "Swan",
  "Swift",
  "Swordfish",
  "Taipan",
  "Takin",
  "Tamarin",
  "Tanager",
  "Tanuki",
  "Tapir",
  "Tarantula",
  "Tarsier",
  "Tasmanian Devil",
  "Tegu Lizard",
  "Tern",
  "Thresher Shark",
  "Thrush",
  "Tiger",
  "Tiger Beetle",
  "Tiger Shark",
  "Tiger Snake",
  "Timber Rattlesnake",
  "Titanoboa",
  "Titmouse",
  "Toad",
  "Tokay Gecko",
  "Tortoise",
  "Toucan",
  "Towhee",
  "Tree Frog",
  "Tree Kangaroo",
  "Triceratops",
  "Triggerfish",
  "Trumpeter Swan",
  "Tuco Tuco",
  "Tundra Swan",
  "Tur",
  "Turkey",
  "Turkey Vulture",
  "Turtle",
  "Turtle Dove",
  "Tyrannosaurus",
  "Uromastyx",
  "Vampire Bat",
  "Vaquita",
  "Veiled Chameleon",
  "Velociraptor",
  "Vicuna",
  "Viper",
  "Vireo",
  "Vole",
  "Vulture",
  "Wallaby",
  "Walrus",
  "Wandering Albatross",
  "Warthog",
  "Water Buffalo",
  "Water Deer",
  "Water Dragon",
  "Water Monitor",
  "Waxwing",
  "Weasel",
  "Weaver",
  "Whale Shark",
  "White Hawk",
  "White Rhino",
  "Whitetail Deer",
  "Whooping Crane",
  "Wild Boar",
  "Wild Horse",
  "Wild Turkey",
  "Willet",
  "Wolf Snake",
  "Wolverine",
  "Wombat",
  "Wood Duck",
  "Woodcock",
  "Woodpecker",
  "Yak",
  "Zebra",
  "Zebu",
  "Zonkey",
];
